name: kids_guard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  uuid: ^3.0.6

  # Core UI
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  shimmer: ^3.0.0
  readmore: ^3.0.0
  bounce: ^1.0.2
  cached_network_image: ^3.3.1
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.3.0
  

  # State management
  flutter_bloc: ^9.1.1

  # Networking
  http: ^1.5.0

  # Firebase
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  firebase_auth: ^6.1.0
  google_sign_in: ^6.2.1
  youtube_player_flutter: ^9.1.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true   # ✅ المكان الصحيح

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-VariableFont_wght.ttf
